### ISSUE TITLE
underscore in table names

### ISSUE THREAD

**Issue by JKcolab** [simalexan/api-lambda-get-all-dynamodb#1]
Hi,

Is there any reason this doesn't work with tables whose names include the underscore(table_name)?

This is an allowed character for table names in AWS but doesn't seem to be accepted using this Lambda function?

Cheers,

John

**Comment by simalexan** [comment]
Hi there @JKcolab, will take a look at it now

**Comment by simalexan** [comment]
Hey @JKcolab, 
Thank you for reporting this! It was a good catch.
I've fixed that along with another small issue. So, I've released a new version - 1.0.1. 
The version is also available on AppRepo - 
https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:375983427419:applications~api-lambda-get-all-dynamodb

Hope it wasn't a too big of a problem!

**Comment by JKcolab** [comment]
Hi @simalexan,

Thank you. This morning, however, I tried to install it (several times on a MBP) and got UPDATE_FAILED on the resources DynamoDBTable and GetAllLambdaRole.

Cheers,

John

**Comment by simalexan** [comment]
@JKcolab Hi again,

can you delete the stack and try to deploy again? It should work, there is probably an error as its trying to update the old stack.

**Comment by simalexan** [comment]
@JKcolab hi again, in case you were using some of my other `api-lambda-...-dynamodb` serverless components, wanted let you know that I've even updated with minor fixes them too. They were just minor fixes regarding the data table underscore character you mentioned and README changes to see the Roadmap for each component.
